language: ruby
sudo: false
rvm: 2.3.0
cache:
  bundler: true
  directories:
    - node_modules
script: ./script/cibuild
before_install:
  - nvm install node
  - node --version
  - export PATH=$PWD/node_modules/.bin:$PATH
  - npm install
  - npm install phantomjs-prebuilt
  - phantomjs --version
env:
  - JQUERY_VERSION: 1.8.0
  - JQUERY_VERSION: 2.2.0
