language: ruby
sudo: false
rvm: 2.3.0
cache:
  bundler: true
  directories:
    - node_modules
script: ./script/cibuild
before_install:
  - nvm install node
  - node --version
  - npm install
  - echo $PATH
  - "[[ $(phantomjs --version) > '2' ]] || npm install -g phantomjs-prebuilt"
  - which phantomjs && phantomjs --version
env:
  - JQUERY_VERSION: 1.8.0
  - JQUERY_VERSION: 2.2.0
