language: ruby
sudo: false
rvm: 2.3.0
cache:
  bundler: true
  directories:
    - $HOME/.npm
    - node_modules
    - travis_phantomjs
script: ./script/cibuild
before_install:
  - export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - ./script/install_phantomjs
  - nvm install node
  - npm install
  - node --version
  - phantomjs --version
  - ruby --version
env:
  - JQUERY_VERSION: 1.8.0
  - JQUERY_VERSION: 2.2.0
